export const INCREMENT_VALUE = 'INCREMENT_VALUE'
export const DECREMENT_VALUE = 'DECREMENT_VALUE'

export const GET_MEDICINE = 'GET_MEDICINE'


export const SIGNUP_USER = 'SIGNUP_USER'
export const SIGNIN_USER = 'SIGNIN_USER'
export const SIGNNED_USER = 'SIGNNED_USER'
export const LOGOUT_USER ='LOGOUT_USER'
export const LOGGEDOUT_USER ='LOGGEDOUT_USER'
export const EMAIL_VERIFIYE = 'EMAIL_VERIFIY'


export const SET_ALERT = 'SET_ALERT'
export const RESET_ALERT = 'RESET_ALERT'

